# Site settings
title: HistoryOut
description: Free Export Chrome History Extension. Export Chrome History in Excel-readable CSV, JSON or HTML formats. Use custom date ranges and customize the output fields.
url: "https://historyout.site"

# Theme settings
theme: jekyll-theme-cayman
show_downloads: true

# SEO settings
author:
  name: Saulius
  url: "https://historyout.site"

# Social links (used by jekyll-seo-tag)
social:
  name: HistoryOut
  links:
    - "https://chrome.google.com/webstore/detail/historyout/idohnkdgejocejlkihihonhemndpiiei"

# Language settings
lang: en

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Services
google_site_verification: "J9EsmoQ_afZAfv1vTpVgo5bu_xHrSMfvtdjN_fUqgrs"
google_analytics: "G-08VGKYN4DC"
